### PR TITLE
fix: add auto reconnect again

### PR DESCRIPTION
**Pull request by Istador**
Alternative to #57:
- Using `SocketClient::tryReconnect()` again instead of adding back `Client::restartConnection()` from the reconnect button.
- Don't give up after 5 attempts.

### CODE REVIEW

**Comment by speyejack** [comment]
This will probably have some synchronization issues as it doesn't fully reset the client, but the server probably will assume a full reset. As such, it may have issues like the original reconnect button did.

**Comment by Istador** [comment]
What does need additional resetting?

The server and the other clients will resend important packets, to update the reconnecting client to the current shared game state.

The server will assume this as a reconnect and not a full reset because of this:
https://github.com/CraftyBoss/SuperMarioOdysseyOnline/blob/f27875f65f30aa081e7f12dd9806b3c398dcc4e7/source/server/SocketClient.cpp#L117-L122

It's not the code of the reconnect button, but the code of the automatic reconnect that was there before and most of the time worked fine, unless for rare synchronization issues that should mostly be handled now. (The biggest issues with the reconnect button was probably by people trying to change servers with it.)

The only thing that I can think of that I haven't looked into that might lead to problems is the player list.
On a reconnect the client gets send the other connected clients again, so it will know about new players.
But I don't know if it cleans up the playerlist beforehand. Because if a disconnect of another player happened in-between that might be missed by the reconnecting client?

**Comment by speyejack** [comment]
The other one basically shuts down both threads and clears the message queues along with trying to send a disconnect message if possible. Which resets a lot of the communication. Though resetting the actors probably isn't the worst idea either.... that's what `stopConnection` does do, I think. 

Sorry, the reason I made the comparison with the reconnect button was just that it didn't really do any state resetting, and that's what I was originally trying to solve when I redid the `Client::restartConnection()` in the udp PR. 

I am mainly worried that the server might drop a client due to some invalid state, then the client tries to resume the connection without doing a soft reset. 

So I guess the main question is, what are the benefits does just calling `SocketClient::tryReconnect()` instead of `Client::restartConnection()`?

**Comment by Istador** [comment]
The disconnect packet is probably not needed at all here, because the socket is dead already and can't be sent packets to? IMHO this would only make sense for a reconnect mechanism for healthy connections (reconnect button).

I was under the impression that if the connection is down, all packets in the send queue are deleted without sending them by the thread processing them. So I don't know if emptying and waiting for that thread is necessary? If it makes sense, or might be cleaner, then that could be added to `tryReconnect()` as well (I think `tryReconnect()` was written as it is before the queues were added to the mod?).

I find it's cleaner to have the reconnect code inside of `SocketClient` instead of inside of `Client`.
`Client::restartConnection()` mostly delegates to `SocketClient` anyway. Not sure about the variables it modifies on the `Client` instance though. I would think that these things are set at other places as well based on the returned return value of `tryReconnect()`? Though I'm not sure.

**Comment by speyejack** [comment]
Yeh, the disconnect packet could probably go, it was a relic from previously. I'm not sure if theres a chance for the socket to ever be open so at that point it would basically be a waste to send the packet. 

No, I believe the send function just returns false if the connection is not connected, so the queue will never be drained. However, currently the client manages the the read/write thread for the socket, so restarting the threads within the socket client is probably a bad idea. 

It also might be easier in the future if the client is doing the reset, as if we find we need to do any reset of client state it wont require another refactor as the client will be doing the reset. 

Also i asked Sanae to provide some feedback, so that we get some insight from the original authors.

**Pull request merged**
